version: 2.1

jobs:
  runner-init:
    machine: true
    resource_class: vignesh_tw/3080ti
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sudo lshw


workflows:
  testing:
    jobs:
      - runner-init