version: 2.1

jobs:
  Initialize PC:
    machine: true
    resource_class: vignesh_tw/3080ti
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: lshw
  Configure ADE:
    machine: true
    resource_class: vignesh_tw/3080ti
    steps:
      - run: ade --version

  Build Autoware:
    machine: true
    resource_class: vignesh_tw/3080ti
    steps:
      - run: |
          mkdir -p ~/adehome
          cd ~/adehome
          touch .adehome
          echo ".aderc-amd64-foxy" >> ~/adehome/.aderc
          ls -a
          cd AutowareAuto
          ade start --update --enter

workflows:
  build-test-deploy:
    jobs:
      - Initialize PC
      - Configure ADE:
          requires:
            - "Initialize PC"
      - Build Autoware:
          requires:
            - "Configure ADE"